# Generated by Django 6.0 on 2025-12-11 07:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubTitleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_language', models.CharField(max_length=10, verbose_name='زبان اصلی')),
                ('primary_subtitle', ckeditor.fields.RichTextField(verbose_name='زیر نویس اولیه')),
                ('cleaned_subtitle', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='زیرنویس پاکسازی شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'پردازش زیر نویس',
                'verbose_name_plural': 'پردازش زیر نویس',
                'ordering': ['-created_at'],
            },
        ),
    ]
